# Generated by Django 3.2 on 2021-05-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
